Changes to compiler driver.  More sophisticated about finding rts.c. set_env provides shortcuts and sets env var. Add better testing setup under Treelang/examples.

diff --git a/TreeLang/examples/Makefile b/TreeLang/examples/Makefile
--- a/TreeLang/examples/Makefile
+++ b/TreeLang/examples/Makefile
@@ -4,6 +4,8 @@ default: valid
 
 # Run the tests straight through Racket
 valid: treelang_lib
+	@echo "\nGenerating canonical answers from Racket:"
+	@echo "-----------------------------------------"
 	for f in `ls test*.sexp`; do racket $$f | tee $$f.ans; done
 
 invalid: treelang_lib
@@ -11,14 +13,39 @@ invalid: treelang_lib
 
 test:
 	$(MAKE) parse_all
+	$(MAKE) run_tests
+
+TREEC= stack exec -- treec
 
 parse_all: 
 	stack build
 	for f in `ls *.sexp`; do \
           echo "Parsing $$f"; \
-          stack exec -- treec --parse $$f; done
+          $(TREEC) --parse $$f; done
+
+PASSING_TESTS= test00_add.sexp
+
+# let this be a proxy for the lot of them:
+test00_add.sexp.ans:
+	$(MAKE) valid
+
+# Run the tests that work:
+run_tests: test00_add.sexp.ans
+	@echo "\n Compiling and running tests through our compiler:"
+	@echo "--------------------------------------------------"
+	stack build
+	for f in $(PASSING_TESTS); do \
+          $(TREEC) --run $$f > $$f.out; \
+          echo "Now check expected $$f.ans, versus received, $$f.out"; \
+          diff $$f.ans $$f.out || (echo "ERROR: Answers differed!"; exit 1); \
+          echo "  -> Success."; \
+        done
 
 treelang_lib:
 	raco make -v ../treelang.rkt 
+
+clean:
+	rm -f *.exe *.o *.c *.ans *.out
+	cd error/; rm -f *.exe *.o *.c *.ans *.out
 
 .PHONY: run_racket treelang_lib
