Change IfEqT to IfT.  Add LetTrivT.  Push EqP through Target.

diff --git a/TreeLang/examples/Makefile b/TreeLang/examples/Makefile
--- a/TreeLang/examples/Makefile
+++ b/TreeLang/examples/Makefile
@@ -22,22 +22,31 @@ parse_all:
           echo "Parsing $$f"; \
           $(TREEC) --parse $$f; done
 
-PASSING_TESTS= test00_add.sexp
+PASSING_TESTS= test00_add test01_if test02_arith
 # FIX THESE: All are blocked on something.  Then move them to the above list:
-#  test02 -- cursorize/let
-#  test03 -- bad C code
-#  test04 -- fromJust/Nothing in flatten
-#  test04b -- cursorize/mkprod
-#  test05 -- cursorize tail Apps
-#  test05b -- cursorize/let
-#  test06  -- cursorize/let
-#  test07  -- cursorize/TimeIt
-#  test08  -- no dictionaries yet
-#  test09  -- fail on Compile.hs nonexhaustive
+#  test03  -- flatten fromJust
+#  test03b -- MkTrue typeExp
+
+#  test04  -- MkTrue typeExp
+#  test04b -- ''
+#  test04c -- lower needs detuple
+#  test05  -- lower/typ'
+#  test05b -- ''
+#  test06  -- lower datacon
+#  test07  -- lower Time
+#  test08  -- parsing empty-dict
+#  test08b -- ''
+#  test08c -- ''
+#  test09  -- lower/typ'
+#  test10  -- codegenTail line 235
+#  test15  -- lower/typ'
+
 
 # let this be a proxy for the lot of them:
 test00_add.sexp.ans:
 	$(MAKE) valid
+
+TREECARGS ?= ""
 
 # Run the tests that work:
 run_tests: test00_add.sexp.ans
@@ -45,11 +54,27 @@ run_tests: test00_add.sexp.ans
 	@echo "--------------------------------------------------"
 	stack build
 	for f in $(PASSING_TESTS); do \
-          $(TREEC) --run $$f > $$f.out; \
+          $(TREEC) --run $(TREECARGS) $$f.sexp > $$f.sexp.out; \
           echo "Now check expected $$f.ans, versus received, $$f.out"; \
-          diff $$f.ans $$f.out || (echo "ERROR: Answers differed!"; exit 1); \
+          diff $$f.sexp.ans $$f.sexp.out || (echo "ERROR: Answers differed!"; exit 1); \
           echo "  -> Success."; \
         done
+
+PACKED_TESTS= test00_add 
+
+# Run the tests that work under the packed regime:
+run_tests_packed: 
+
+PACKED_TESTS= test00_add 
+#  test04b -- cursorize/mkprod
+#  test05  -- cursorize tail Apps
+#  test05b -- cursorize/let
+#  test06  -- cursorize/let
+#  test07  -- cursorize/TimeIt
+#  test08  -- no dictionaries yet
+#  test09  -- fail on Compile.hs nonexhaustive
+
+
 
 treelang_lib:
 	raco make -v ../treelang.rkt 
